### ISSUE TITLE
Getting error for stopwords

### ISSUE THREAD

**Issue by mehullala** [akashp1712/nlp-akash#1]
Hello,
I am trying to run the code but getting this error which I am not able to resolve:

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

I have tried to add stopwords files (downloaded form NLTK website) but it's not working.

**Comment by akashp1712** [comment]
Thanks, @mehullala, for raising the concern.

Please try to download and install stopwords with root permission.
And if you're using windows then download it using via cmd with admin privileges. (run as admin)

Please try once and let me know.

**Comment by mehullala** [comment]
Thank you
